final colorIt = {
  'it': [
    {"name": "Albicocca", "hex": "fbceb1"},
    {"name": "Amaranto", "hex": "E52B50"},
    {"name": "Ambra", "hex": "FFBF00"},
    {"name": "Ametista", "hex": "884DA7"},
    {"name": "Anguria", "hex": "fc6c85"},
    {"name": "Antracite", "hex": "293133"},
    {"name": "Aragosta", "hex": "ed7465"},
    {"name": "Arancione", "hex": "FFA500"},
    {"name": "Ardesia", "hex": "708090"},
    {"name": "Argento", "hex": "C0C0C0"},
    {"name": "Asparago", "hex": "87a96b"},
    {"name": "Avio", "hex": "5D8AA8"},
    {"name": "Avorio", "hex": "FFFFF0"},
    {"name": "Azalea", "hex": "d3305d"},
    {"name": "Azzurro", "hex": "007fff"},
    {"name": "Azzurro fiordaliso", "hex": "ABCDEF"},
    {"name": "Beige", "hex": "f5f5dc"},
    {"name": "Beige-oliva chiaro", "hex": "908435"},
    {"name": "Beige verdastro", "hex": "BEBD7F"},
    {"name": "Bianco", "hex": "FFFFFF"},
    {"name": "Bianco antico", "hex": "FFFEEF"},
    {"name": "Bianco anti-flash", "hex": "F2F3F4"},
    {"name": "Bianco di titanio", "hex": "FAEBD7"},
    {"name": "Bianco di zinco", "hex": "FEFEE9"},
    {"name": "Bianco fantasma", "hex": "F8F8FF"},
    {"name": "Bianco floreale", "hex": "FFFAF0"},
    {"name": "Bianco fumo", "hex": "F5F5F5"},
    {"name": "Bianco Navajo", "hex": "FFDEAD"},
    {"name": "Biscotto", "hex": "FFE4C4"},
    {"name": "Bistro", "hex": "3D2B1F"},
    {"name": "Blu", "hex": "0000ff"},
    {"name": "Blu acciaio", "hex": "4682B4"},
    {"name": "Blu alice", "hex": "F0F8FF"},
    {"name": "Blu Bondi", "hex": "0095B6"},
    {"name": "Blu cadetto", "hex": "5F9EA0"},
    {"name": "Blu ceruleo", "hex": "2A52BE"},
    {"name": "Blu comando stellare", "hex": "007BB8"},
    {"name": "Blu di Persia", "hex": "1C39BB"},
    {"name": "Blu di Prussia", "hex": "003153"},
    {"name": "Blu Dodger", "hex": "1e90ff"},
    {"name": "Blu elettrico", "hex": "003399"},
    {"name": "Blu Klein", "hex": "002FA7"},
    {"name": "Blu marino", "hex": "000080"},
    {"name": "Blu notte", "hex": "343A90"},
    {"name": "Blu oltremare", "hex": "120A8F"},
    {"name": "Blu reale", "hex": "4169E1"},
    {"name": "Bordeaux", "hex": "800000"},
    {"name": "Borgogna", "hex": "800020"},
    {"name": "Bronzo", "hex": "CD7F32"},
    {"name": "Bronzo antico", "hex": "75663F"},
    {"name": "Camoscio", "hex": "F0DC82"},
    {"name": "Carbone", "hex": "050402"},
    {"name": "Cardo", "hex": "D8BFD8"},
    {"name": "Carminio", "hex": "960018"},
    {"name": "Carta da zucchero", "hex": "e0ffff"},
    {"name": "Castagno", "hex": "CD5C5C"},
    {"name": "Castagno scuro", "hex": "986960"},
    {"name": "Castano chiaro", "hex": "DDADAF"},
    {"name": "Catrame", "hex": "D2B48C"},
    {"name": "Catrame scuro", "hex": "918151"},
    {"name": "Celadon", "hex": "ACE1AF"},
    {"name": "Celeste", "hex": "99CBFF"},
    {"name": "Ceruleo", "hex": "007BA7"},
    {"name": "Ceruleo scuro", "hex": "08457E"},
    {"name": "Chartreuse", "hex": "7fff00"},
    {"name": "Ciano", "hex": "00ffff"},
    {"name": "Ciliegia", "hex": "DE3163"},
    {"name": "Cioccolato", "hex": "D2691E"},
    {"name": "Cobalto", "hex": "0047AB"},
    {"name": "Conchiglia", "hex": "FFF5EE"},
    {"name": "Corallo", "hex": "ff7f50"},
    {"name": "Crema", "hex": "FFFDD0"},
    {"name": "Cremisi", "hex": "dc143c"},
    {"name": "Denim", "hex": "1560BD"},
    {"name": "Denim chiaro", "hex": "5E86C1"},
    {"name": "Eliotropo", "hex": "DF73FF"},
    {"name": "Ecru", "hex": "C2B280"},
    {"name": "Fiore di granturco", "hex": "6495ED"},
    {"name": "Foglia di tè", "hex": "008080"},
    {"name": "Fucsia", "hex": "f400a1"},
    {"name": "Fucsia Bordesto Lillato", "hex": "E0AFEE"},
    {"name": "Fulvo", "hex": "EBB55F"},
    {"name": "Gainsboro", "hex": "DCDCDC"},
    {"name": "Giada", "hex": "00A86B"},
    {"name": "Giallo", "hex": "ffff00"},
    {"name": "Giallo miele", "hex": "A98307"},
    {"name": "Giallo Napoli", "hex": "F7E89F"},
    {"name": "Giallo pastello", "hex": "FFFF66"},
    {"name": "Giallo sabbia", "hex": "C6A664"},
    {"name": "Giallo segnale", "hex": "E5BE01"},
    {"name": "Giallo scuolabus", "hex": "ffd800"},
    {"name": "Glicine", "hex": "C9A0DC"},
    {"name": "Granata", "hex": "7B1B02"},
    {"name": "Grano", "hex": "F5DEB3"},
    {"name": "Grigio", "hex": "808080"},
    {"name": "Grigio 5%", "hex": "F7F7F7"},
    {"name": "Grigio 10%", "hex": "EFEFEF"},
    {"name": "Grigio 20%", "hex": "D2D2D2"},
    {"name": "Grigio 30%", "hex": "B2B2B2"},
    {"name": "Grigio 40%", "hex": "8F8F8F"},
    {"name": "Grigio 50%", "hex": "808080"},
    {"name": "Grigio 60%", "hex": "5F5F5F"},
    {"name": "Grigio 70%", "hex": "4F4F4F"},
    {"name": "Grigio 75%", "hex": "404040"},
    {"name": "Grigio 80%", "hex": "2F2F2F"},
    {"name": "Grigio asparago", "hex": "465945"},
    {"name": "Grigio ardesia scuro", "hex": "2F4F4F"},
    {"name": "Grigio ardesia chiaro", "hex": "778899"},
    {"name": "Grigio cenere", "hex": "E4E5E0"},
    {"name": "Grigio rosso chiaro", "hex": "D0AFAE"},
    {"name": "Grigio tè verde", "hex": "CADABA"},
    {"name": "Grigio topo", "hex": "646B63"},
    {"name": "Incarnato prugna", "hex": "CC8899"},
    {"name": "Indaco", "hex": "4B0082"},
    {"name": "Indaco elettrico", "hex": "6F00FF"},
    {"name": "Indaco scuro", "hex": "310062"},
    {"name": "International Klein Blue", "hex": "002FA7"},
    {"name": "Isabella", "hex": "F4F0EC"},
    {"name": "Kaki", "hex": "C3B091"},
    {"name": "Kaki chiaro", "hex": "F0E68C"},
    {"name": "Kaki scuro", "hex": "BDB76B"},
    {"name": "Lampone", "hex": "E30B5C"},
    {"name": "Lavanda", "hex": "E6E6FA"},
    {"name": "Lavanda pallido", "hex": "DABAD0"},
    {"name": "Lavanda rosata", "hex": "FFF0F5"},
    {"name": "Limone", "hex": "FDE910"},
    {"name": "Limone crema", "hex": "FFFACD"},
    {"name": "Lilla", "hex": "C8A2C8"},
    {"name": "Lime", "hex": "CCFF00"},
    {"name": "Lino", "hex": "FAF0E6"},
    {"name": "Magenta", "hex": "FF00FF"},
    {"name": "Magenta chiaro", "hex": "F984E5"},
    {"name": "Magnolia", "hex": "F8F4FF"},
    {"name": "Malva", "hex": "993366"},
    {"name": "Malva chiaro", "hex": "996666"},
    {"name": "Mandarino", "hex": "FFCC00"},
    {"name": "Marrone", "hex": "964B00"},
    {"name": "Marrone chiaro", "hex": "CD853F"},
    {"name": "Marrone pastello", "hex": "987654"},
    {"name": "Marrone-rosso", "hex": "993300"},
    {"name": "Marrone sabbia chiaro", "hex": "DABDAB"},
    {"name": "Marrone scuro", "hex": "654321"},
    {"name": "Melanzana", "hex": "990066"},
    {"name": "Mogano", "hex": "C04000"},
    {"name": "Nero", "hex": "000000"},
    {"name": "Ocra", "hex": "CC7722"},
    {"name": "Olivina", "hex": "9AB973"},
    {"name": "Orchidea", "hex": "DA70D6"},
    {"name": "Oro", "hex": "ffd700"},
    {"name": "Oro vecchio", "hex": "CFB53B"},
    {"name": "Ottone antico", "hex": "CC9966"},
    {"name": "Papaia", "hex": "FFEFD5"},
    {"name": "Pera", "hex": "D1E231"},
    {"name": "Pervinca", "hex": "CCCCFF"},
    {"name": "Pesca", "hex": "FFE5B4"},
    {"name": "Pesca scuro", "hex": "FFDAB9"},
    {"name": "Pesca-arancio", "hex": "FFCC99"},
    {"name": "Pesca-giallo", "hex": "FADFAD"},
    {"name": "Pistacchio", "hex": "93C572"},
    {"name": "Platino", "hex": "E5E4E2"},
    {"name": "Porpora", "hex": "B20000"},
    {"name": "Prugna", "hex": "660066"},
    {"name": "Rame", "hex": "b87333"},
    {"name": "Registration black", "hex": "000000"},
    {"name": "Rosa", "hex": "FFC0CB"},
    {"name": "Rosa arancio", "hex": "FF9966"},
    {"name": "Rosa medio", "hex": "DB244F"},
    {"name": "Rosa Mountbatten", "hex": "997A8D"},
    {"name": "Rosa pallido", "hex": "FADADD"},
    {"name": "Rosa pastello", "hex": "FFD1DC"},
    {"name": "Rosa scuro", "hex": "E75480"},
    {"name": "Rosa shocking", "hex": "FC0FC0"},
    {"name": "Rosa vivo", "hex": "FF007F"},
    {"name": "Rosso", "hex": "FF0000"},
    {"name": "Rosso aragosta", "hex": "cc5500"},
    {"name": "Rosso cardinale", "hex": "C41E3A"},
    {"name": "Rosso corsa", "hex": "CC0000"},
    {"name": "Rosso Falun", "hex": "801818"},
    {"name": "Rosso fragola", "hex": "CE3018"},
    {"name": "Rosso fuoco", "hex": "A61022"},
    {"name": "Rosso mattone", "hex": "C41E3A"},
    {"name": "Rosso mattone chiaro", "hex": "BD8E80"},
    {"name": "Rosso pomodoro", "hex": "FF6347"},
    {"name": "Rosso pompeiano", "hex": "D21F1B"},
    {"name": "Rosso rosa", "hex": "FF6088"},
    {"name": "Rosso sangue", "hex": "500000"},
    {"name": "Rosso segnale", "hex": "A52019"},
    {"name": "Rosso Tiziano", "hex": "BA6262"},
    {"name": "Rosso veneziano", "hex": "C80815"},
    {"name": "Rosso violaceo", "hex": "C71585"},
    {"name": "Rosso violetto chiaro", "hex": "DB7093"},
    {"name": "Rubino", "hex": "410012"},
    {"name": "Sabbia", "hex": "F4A460"},
    {"name": "Salmone", "hex": "FF8C69"},
    {"name": "Salmone scuro", "hex": "E9967A"},
    {"name": "Sangria", "hex": "92000A"},
    {"name": "Scarlatto", "hex": "FF2400"},
    {"name": "Scarlatto scuro", "hex": "560319"},
    {"name": "Seppia", "hex": "704214"},
    {"name": "Solidago", "hex": "DAA520"},
    {"name": "Solidago scuro", "hex": "B8860B"},
    {"name": "Tan", "hex": "D2B48C"},
    {"name": "Tenné", "hex": "CD5700"},
    {"name": "Terra d’ombra", "hex": "635147"},
    {"name": "Terra d’ombra bruciata", "hex": "8A3324"},
    {"name": "Terra di Siena", "hex": "E97451"},
    {"name": "Terra di Siena bruciata", "hex": "531B00"},
    {"name": "Testa di moro", "hex": "754909"},
    {"name": "Tè verde", "hex": "D0F0C0"},
    {"name": "Tè verde scuro", "hex": "BADBAD"},
    {"name": "Tronco", "hex": "79443B"},
    {"name": "Turchese", "hex": "30D5C8"},
    {"name": "Turchese chiaro", "hex": "08E8DE"},
    {"name": "Turchese pallido", "hex": "99FFCC"},
    {"name": "Turchese scuro", "hex": "116062"},
    {"name": "Turchese Perla Mistica", "hex": "99FFCC"},
    {"name": "Uovo di pettirosso", "hex": "00CCCC"},
    {"name": "Uovo di pettirosso chiaro", "hex": "96DED1"},
    {"name": "Verde", "hex": "00ff00"},
    {"name": "Verde Caraibi", "hex": "00CC99"},
    {"name": "Verde foresta", "hex": "228b22"},
    {"name": "Verde chiaro", "hex": "66FF00"},
    {"name": "Verde-giallo", "hex": "ADFF2F"},
    {"name": "Verde marino", "hex": "2E8B57"},
    {"name": "Verde marino medio", "hex": "3CB371"},
    {"name": "Verde marino scuro", "hex": "8FBC8F"},
    {"name": "Verde menta", "hex": "98FF98"},
    {"name": "Verde menta chiaro", "hex": "A6FBB2"},
    {"name": "Verde muschio", "hex": "ADDFAD"},
    {"name": "Verde oliva", "hex": "808000"},
    {"name": "Verde olivastro", "hex": "6B8E23"},
    {"name": "Verde oliva scuro", "hex": "556B2F"},
    {"name": "Verde pastello", "hex": "77DD77"},
    {"name": "Verde pino", "hex": "01796F"},
    {"name": "Verde primavera", "hex": "00FF7F"},
    {"name": "Verde primavera scuro", "hex": "177245"},
    {"name": "Verde ufficio", "hex": "008000"},
    {"name": "Verde smeraldo", "hex": "50c878"},
    {"name": "Verde Veronese", "hex": "40826D"},
    {"name": "Vermiglio", "hex": "FF4D00"},
    {"name": "Viola", "hex": "8F00ff"},
    {"name": "Viola chiaro", "hex": "9F00FF"},
    {"name": "Viola melanzana", "hex": "991199"},
    {"name": "Vinaccia", "hex": "C0007F"},
    {"name": "Zafferano", "hex": "F4C430"},
    {"name": "Zafferano profondo", "hex": "FF9933"},
  ]
};
