final oracleIt = {
  'it': [
    {"label": "I segnali indicano sì."},
    {"label": "Sì."},
    {"label": "Senza dubbio."},
    {"label": "Le mie fonti dicono no."},
    {"label": "Per come la vedo io, sì."},
    {"label": "Puoi contarci."},
    {"label": "Concentrati e richiedilo."},
    {"label": "Le prospettive non sono così buone."},
    {"label": "È decisamente così."},
    {"label": "Ora è meglio non dirtelo..."},
    {"label": "Sono molto dubbioso."},
    {"label": "Sì, decisamente."},
    {"label": "È certo."},
    {"label": "Non posso predirlo ora."},
    {"label": "Molto probabilmente."},
    {"label": "Richiedilo più tardi."},
    {"label": "La mia risposta è no."},
    {"label": "Le prospettive sono buone."},
    {"label": "Non contarci"},
    {"label": "Sì, a tempo debito."},
    {"label": "Le mie fonti dicono no."},
    {"label": "Decisamente no."},
    {"label": "Sì."},
    {"label": "Devi aspettare."},
    {"label": "Ho i miei dubbi."},
    {"label": "Le prospettive sono così così."},
    {"label": "Mi sembra buono!"},
    {"label": "Chi lo sa?"},
    {"label": "Mi piace!"},
    {"label": "Probabilmente."},
    {"label": "Stai scherzando?"},
    {"label": "Fallo!"},
    {"label": "Non scommetterci."},
    {"label": "Dimenticalo."},
  ],
};
